async function fetchYoutubeCookiesNetscape() {
  const all = [];
  const urls = [
    'https://www.youtube.com/',
    'https://youtube.com/',
    'https://www.google.com/',
    'https://accounts.google.com/',
  ];

  for (const url of urls) {
    try {
      const list = await chrome.cookies.getAll({ url });
      all.push(...list);
    } catch {}
  }

  for (const domain of ['youtube.com', '.youtube.com', 'google.com', '.google.com']) {
    try {
      const list = await chrome.cookies.getAll({ domain });
      all.push(...list);
    } catch {}
  }

  const authNames = new Set([
    'SID', 'HSID', 'SSID', 'APISID', 'SAPISID', 'LOGIN_INFO', 'NID', 'PREF',
    '__Secure-1PSID', '__Secure-3PSID', '__Secure-1PAPISID', '__Secure-3PAPISID',
    '__Secure-1PSIDTS', '__Secure-3PSIDTS', '__Secure-1PSIDCC', '__Secure-3PSIDCC',
    'VISITOR_INFO1_LIVE', 'YSC', 'SOCS',
  ]);

  const seen = new Set();
  const filtered = [];

  for (const c of all) {
    const key = `${c.domain}|${c.name}|${c.path}`;
    if (seen.has(key)) continue;
    seen.add(key);

    const onYoutube = c.domain.includes('youtube');
    const googleAuth = c.domain.includes('google') && (
      authNames.has(c.name) || c.name.startsWith('__Secure')
    );

    if (onYoutube || googleAuth) {
      filtered.push(c);
    }
  }

  if (filtered.length < 3) return '';

  const lines = [
    '# Netscape HTTP Cookie File',
    '# This file is generated by Кактус загрузка',
    '',
  ];

  for (const c of filtered) {
    let domain = c.domain;
    if (!domain.startsWith('.')) {
      domain = '.' + domain;
    }
    const path = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const exp = Math.floor(c.expirationDate || (Date.now() / 1000 + 86400 * 365));
    lines.push(`${domain}\tTRUE\t${path}\t${secure}\t${exp}\t${c.name}\t${c.value}`);
  }

  return lines.join('\n');
}

async function syncYoutubeCookies() {
  const cookies = await fetchYoutubeCookiesNetscape();
  if (!cookies) return null;

  await chrome.storage.local.set({ ytCookies: cookies });
  return cookies;
}
