async function fetchYoutubeCookiesNetscape() {
  const all = [];
  const urls = [
    'https://www.youtube.com/',
    'https://youtube.com/',
    'https://www.google.com/',
  ];

  for (const url of urls) {
    const list = await chrome.cookies.getAll({ url });
    all.push(...list);
  }

  const extra = await chrome.cookies.getAll({ domain: 'youtube.com' });
  const google = await chrome.cookies.getAll({ domain: 'google.com' });
  all.push(...extra, ...google);

  const googleKeep = new Set([
    'SID', 'HSID', 'SSID', 'APISID', 'SAPISID', 'LOGIN_INFO', 'NID', 'PREF', '__Secure-1PSID', '__Secure-3PSID',
  ]);

  const seen = new Set();
  const filtered = [];

  for (const c of all) {
    const key = `${c.domain}|${c.name}|${c.path}`;
    if (seen.has(key)) continue;
    seen.add(key);

    if (c.domain.includes('youtube') || googleKeep.has(c.name)) {
      filtered.push(c);
    }
  }

  if (!filtered.length) return '';

  const lines = [
    '# Netscape HTTP Cookie File',
    '# This file is generated by Кактус загрузка',
    '',
  ];

  for (const c of filtered) {
    let domain = c.domain;
    if (!domain.startsWith('.')) {
      domain = '.' + domain;
    }
    const path = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const exp = Math.floor(c.expirationDate || (Date.now() / 1000 + 86400 * 365));
    lines.push(`${domain}\tTRUE\t${path}\t${secure}\t${exp}\t${c.name}\t${c.value}`);
  }

  return lines.join('\n');
}

async function syncYoutubeCookies() {
  const cookies = await fetchYoutubeCookiesNetscape();
  if (!cookies) return null;

  await chrome.storage.local.set({ ytCookies: cookies });
  return cookies;
}
